### ISSUE TITLE
Building image

### ISSUE THREAD

**Issue by boboxx** [radredgreen/wyrecam#1]
What kind of environemnt is required to build this image? I'm really interested in getting this cameraw working natively with HomeKit!

Very nice project :)

**Comment by radredgreen** [comment]
HomeKit doesn't work yet.  So far only RTSP streaming.  You can get an image, ready for installation, in the releases link.  Connect to the camera at rtsp://ipaddress/stream

**Comment by boboxx** [comment]
ah cool I got it working! Is it notmal that the colours are way off?
![Screenshot 2023-03-22 at 1 47 36 PM](https://user-images.githubusercontent.com/15091037/226977995-6353b309-b572-437c-8f9a-db60aedf38a1.png)

**Comment by radredgreen** [comment]
The IR filter is controlled by a GPIO pin which still needs to be controlled based on the brightness detected in the image.  So it's expected for now.

**Comment by boboxx** [comment]
understood, thank!

**Comment by radredgreen** [comment]
@boboxx Homekit and colors fixed!
