### ISSUE TITLE
bootloader

### ISSUE THREAD

**Issue by gtxaspec** [radredgreen/wyrecam#4]
@radredgreen not really an issue, just wanted to let you know I appreciate your work with wyrecam, and we've forked the bootloader from openipc, fixed a lot of issues, and aded new features, maybe you wanted to look:

https://github.com/gtxaspec/u-boot-ingenic

maybe you would have success using it with wyrecam!

**Comment by radredgreen** [comment]
@gtxaspec Thanks for letting me know.  I had to do some work on the boot loader to get the clocks all running at the right rate for the video codec.  Any other improvements I should know about?  I've been focusing on the HomeKit side of this project lately.

**Comment by gtxaspec** [comment]
The original code base had significant challenges, including numerous overrides and redefinition issues, which we have addressed. However, we haven't made any adjustments to the clock settings. Could you elaborate on the modifications you implemented in that area? So far, we haven't encountered any video-related issues. 

We've also enhanced functionality by introducing USB Ethernet support in U-Boot, enabling updates via an SD card through an `autoupdate-full.bin` file, and adding support for ext2/4 file systems. Other notable improvements include the ability to configure GPIOs directly from the U-Boot command line, hush scripting capabilities, options for booting a custom kernel from an SD card, and JFFS2 support. A significant upgrade has been the implementation of automatic partitioning, which has allowed us to optimize the partition layout, resulting in a substantially larger overlay partition.

I don't use homekit personally but any progress for our devices is exciting!

**Comment by radredgreen** [comment]
See the changes I had to make for stable video here
https://github.com/radredgreen/wyrecam/commit/f707b01434d91b99091f38d23a3380f4f424c4f8

Before this I was getting strange errors and crashes.  Took quite a while to diagnose it down to this.  Very frustrating.
